vlog -work work C:/Users/elcio/Documents/MIC1/simulation/modelsim/CONTROL_UNIT_iadd_isub.vwf.vt
vsim -novopt -c -t 1ps -L cycloneii_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.CONTROL_UNIT_vlg_vec_tst
onerror {resume}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/CLOCK}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MBR_IN}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MBR_IN[7]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MBR_IN[6]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MBR_IN[5]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MBR_IN[4]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MBR_IN[3]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MBR_IN[2]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MBR_IN[1]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MBR_IN[0]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[35]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[34]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[33]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[32]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[31]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[30]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[29]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[28]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[27]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[26]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[25]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[24]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[23]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[22]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[21]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[20]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[19]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[18]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[17]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[16]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[15]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[14]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[13]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[12]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[11]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[10]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[9]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[8]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[7]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[6]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[5]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[4]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[3]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[2]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[1]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MIR[0]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC[8]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC[7]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC[6]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC[5]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC[4]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC[3]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC[2]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC[1]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/MPC[0]}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/N}
add wave {CONTROL_UNIT_vlg_vec_tst/i1/Z}
run -all
